// Generated by gencpp from file package1/abccalcResponse.msg
// DO NOT EDIT!


#ifndef PACKAGE1_MESSAGE_ABCCALCRESPONSE_H
#define PACKAGE1_MESSAGE_ABCCALCRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace package1
{
template <class ContainerAllocator>
struct abccalcResponse_
{
  typedef abccalcResponse_<ContainerAllocator> Type;

  abccalcResponse_()
    : r(0)  {
    }
  abccalcResponse_(const ContainerAllocator& _alloc)
    : r(0)  {
  (void)_alloc;
    }



   typedef int64_t _r_type;
  _r_type r;





  typedef boost::shared_ptr< ::package1::abccalcResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::package1::abccalcResponse_<ContainerAllocator> const> ConstPtr;

}; // struct abccalcResponse_

typedef ::package1::abccalcResponse_<std::allocator<void> > abccalcResponse;

typedef boost::shared_ptr< ::package1::abccalcResponse > abccalcResponsePtr;
typedef boost::shared_ptr< ::package1::abccalcResponse const> abccalcResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::package1::abccalcResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::package1::abccalcResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace package1

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::package1::abccalcResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::package1::abccalcResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::package1::abccalcResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::package1::abccalcResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::package1::abccalcResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::package1::abccalcResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::package1::abccalcResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bd10b384903425c126bed4311db62af6";
  }

  static const char* value(const ::package1::abccalcResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbd10b384903425c1ULL;
  static const uint64_t static_value2 = 0x26bed4311db62af6ULL;
};

template<class ContainerAllocator>
struct DataType< ::package1::abccalcResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "package1/abccalcResponse";
  }

  static const char* value(const ::package1::abccalcResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::package1::abccalcResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 r\n\
\n\
";
  }

  static const char* value(const ::package1::abccalcResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::package1::abccalcResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.r);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct abccalcResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::package1::abccalcResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::package1::abccalcResponse_<ContainerAllocator>& v)
  {
    s << indent << "r: ";
    Printer<int64_t>::stream(s, indent + "  ", v.r);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PACKAGE1_MESSAGE_ABCCALCRESPONSE_H
